version: "3.8"

services:

    flask:
      build: ./flask
      container_name: flask
      volumes:
        - ./flask:/app
      environment:
        FLASK_ENV: development
      expose:
        - 8080

    nginx:
      build: ./nginx
      container_name: nginx
      restart: always
      ports:
        - "80:80"
