version: "3.8"
services:
    web:
        build: ./
        ports:
            - '5000:5000'
        volumes:
            - .:/appDock
        environment:
            FLASK_ENV: development
        container_name: bjeCV
